ДЗ к уроку 2

## Практическое задание ч.1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

---


__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   - AB, BA не определено
    
б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   - AB определено, размерность $2 \times 3$
   - BA не определено

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   - AB определено, размерность $8 \times 8$
   - BA определено, размерность $3 \times 3$
    
г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

   - AB, BA определено, размерность $4 \times 4$
    
---


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

**Сумма**

$S=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$

**Произведение**

$S=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$

---


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц
$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


$S=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

---


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 
\end{pmatrix}$.

$AA^{T}=\begin{pmatrix}
17 & 18 & 11  \\ 
18 & 29 & 4  \\ 
11 & 4 & 13 
\end{pmatrix}$.

$A^{T}A=\begin{pmatrix}
45 & 0 \\ 
0 & 14   
\end{pmatrix}$.

---


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [4]:
import numpy

In [13]:
## Задание 2

A = numpy.array(
    [[1, -2], 
     [3, 0]]
)

B = numpy.array(
    [[4, -1], 
     [0, 5]]
)

print(A@B)
print(A+B)

[[  4 -11]
 [ 12  -3]]
[[ 5 -3]
 [ 3  5]]


In [12]:
## Задание 3

A = numpy.array(
    [[1, 7], 
     [3, -6]]
)

B = numpy.array(
    [[0, 5], 
     [2, -1]]
)

C = numpy.array(
    [[2, -4], 
     [1, 1]]
)

print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


In [7]:
## Задание 4

A = numpy.array(
    [[4, 1], 
     [5, -2],
     [2, 3]]
)
print(A.T)
print(A@A.T)
print(A.T.dot(A))

[[ 4  5  2]
 [ 1 -2  3]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

In [4]:
## Задание 5

A = numpy.array([[0, 2, 10],
                 [0, 0, 21]])
  
B = numpy.array([[1, 1],
                 [1, 1],
                 [123, 12]])

def Multiply_Array (array_1, array_2):
    if array_1.ndim == array_2.ndim == 2:
      shape_1 = array_1.shape
      shape_2 = array_2.shape
      new_ar = list()
      if shape_1[1] == shape_2[0]:
        for n_str_ar in range(shape_1[0]): #номер строки первого массива
          for n_col_ar in range(shape_2[1]): #номер столбца второго массива
            new_ar.append(sum(
                [(array_1[n_str_ar, :][n-1])*(array_2[:, n_col_ar][n-1]) for n in range(shape_1[1])]
                )
            )

        new_ar = numpy.array(new_ar)
        new_ar.resize(shape_1[0], shape_2[1])
    return new_ar

print(Multiply_Array(A,B))
A.dot(B)

[[1232  122]
 [2583  252]]


array([[1232,  122],
       [2583,  252]])

## Практическое задание ч.2




__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$detA = \sin{x} \cdot \sin{x} - \cos{x} \cdot (-\cos{x}) = \sin^2{x} + \cos^2{x} = 1$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$detA = 180$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$detA = 1*(45-48) - 2*(36-42) + 3*(32-35) = -3 + 12 - 9 = 0$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = 4*4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 4*2^i$, где i порядок матрицы.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

вырожденная.

$detA = (-2)*(((-14)*13)-(6*7)) - 7*((4*13)-(6*(-3))) - 3 *((4*7)-((-3)*(-14))) = 0$

Определитель равен 0, значит матрица вырожденная.


__4.__ Найти ранг матрицы:

   **а)** $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

1.уберем 3 строку, так как она – сумма первых двух

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$

2.вычтем 2 строку из первой и поменяем их меставми

$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix};$

**Ранг матрицы - 2**

   **б)** $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

1.умножим 2 строку на 0,5

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 1 & 1\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

2.вычтем из 3 строки две 2-ых строки и одну первую.

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 1 & 1\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

3.уберем нулевую строку

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 1 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**Ранг матрицы 3**


In [14]:
# Задание 2

A = numpy.array(
    [[3, 3, 3], 
     [3, 0, 3],
     [0, 3, 3]]
)
numpy.linalg.det(A)

-27.0

In [26]:
# Задание 3

print(
    (-2)*(((-14)*13)-(6*7)) - 7*((4*13)-(6*(-3))) - 3 *((4*7)-((-3)*(-14)))
)

A = numpy.array(
    [[-2, 7, -3], 
     [4, -14, 6],
     [-3, 7, 13]]
)
numpy.linalg.det(A)

0


0.0

In [32]:
# Задание 4
A = numpy.array(
    [[1, 2, 3], 
     [1, 1, 1],
     [2, 3, 4]]
)
print(numpy.linalg.matrix_rank(A))

A = numpy.array(
    [[0, 0, 2, 1],
     [0, 0, 2, 2], 
     [0, 0, 4, 3], 
     [2, 3, 5, 6]]
)
print(numpy.linalg.matrix_rank(A))

2
3
